apiVersion: v2
name: spring-boot-microservice
description: A Helm chart for spring boot microservices on Kubernetes
type: application
version: 1.0.0
appVersion: 1.0.0
keywords:
  - spring boot
  - microservice
maintainers:
  - name: "Andreas Stuerz"
    email: "it-solutions@andreas-stuerz.de"
