apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "etcd-backup.fullname" . }}-scripts
  labels: {{- include "etcd-backup.labels" . | nindent 4 }}
data:
  etcd-snapshot-backup.sh: |-
    #!/bin/sh
    BACKUP_DIR="{{ .Values.volumes.backup_dir.mountpath }}"
    BACKUP_FILE="${BACKUP_DIR}/{{ .Values.cronjob.snapshotFilename }}"

    if [ "${CRONJOB_DEBUG}" = true ]; then
      find ${BACKUP_DIR} -mtime +{{ .Values.cronjob.backupRetention }} -exec ls -la {} \;
    else
      find ${BACKUP_DIR} -mtime +{{ .Values.cronjob.backupRetention }} -exec rm {} \;
    fi

    # take the snapshot
    etcdctl snapshot save ${BACKUP_FILE}

    # verify snapshot
    etcdctl --write-out=table snapshot status ${BACKUP_FILE}

    # secure permission
    chmod {{ .Values.cronjob.snapshotFilepermission }} {{ .Values.cronjob.snapshotFilename }}


